"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect,useState } from "react";
import { motion } from "framer-motion";
import { Building2, CalendarDays, ShieldCheck } from "lucide-react";
import { Button } from "./ui/button";
const Scene=dynamic(()=>import("./campus-scene"),{ssr:false,loading:()=> <div className="scene-fallback">CAMPUS / CONNECTED</div>});
export default function Hero(){const [webgl,setWebgl]=useState(false);useEffect(()=>{try{const canvas=document.createElement("canvas");setWebgl(window.innerWidth>700&&!!canvas.getContext("webgl2"));}catch{setWebgl(false);}},[]);return <main className="landing"><nav className="topbar"><Link href="/" className="brand"><Building2/>SMART CAMPUS</Link><span className="nav-label">ROOM MANAGEMENT SYSTEM</span><Link href="/login">Enter portal</Link></nav><section className="hero"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="hero-copy"><p className="eyebrow">YOUR CAMPUS. IN SYNC.</p><h1>The right room.<br/>At the <em>right time.</em></h1><p className="lead">One connected space for classes, club events and the people who make campus happen.</p><Button asChild><Link href="/login">Enter your portal</Link></Button><div className="hero-note"><ShieldCheck size={16}/> Five roles. One secure campus.</div></motion.div><div className="hero-scene" aria-label="Illustrative low-poly campus">{webgl?<Scene/>:<div className="scene-fallback"><Building2 size={120}/><span>SMART CAMPUS</span><p>Your next class, connected.</p></div>}<div className="scene-caption"><span>01 / CAMPUS OVERVIEW</span><span>Designed around your timetable</span></div></div></section><div className="feature-strip"><span><CalendarDays/>Fixed timetable, flexible changes</span><span><Building2/>650 classrooms across 13 blocks</span><span><ShieldCheck/>Approval before allocation</span></div><footer>SMART CAMPUS ROOM MANAGEMENT SYSTEM <span>College hackathon · First build</span></footer></main>;}
