"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Building2,Users,GraduationCap,CalendarDays,ShieldCheck } from "lucide-react";
import { motion } from "framer-motion";
import Link from "next/link";
import { roles,roleLabels,type Role } from "@/lib/roles";
import { Button } from "./ui/button";
const icons={admin:ShieldCheck,rep:Users,club_member:CalendarDays,faculty:GraduationCap,student:Building2};
const descriptions={admin:"Keep campus running",rep:"Keep your class connected",club_member:"Make space for your events",faculty:"Your classes, in one place",student:"Know where to be next"};
export default function LoginForm({demo}:{demo:boolean}){const router=useRouter();const [role,setRole]=useState<Role>("student");const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function signIn(identifier:string,password:string,isDemo:boolean,selected=role){setBusy(true);setError("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({identifier,password,role:selected,demo:isDemo})});const result=await response.json();if(!response.ok)throw new Error(result.error);router.push("/portal");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to sign in");}finally{setBusy(false);}}
return <main className="login-page"><Link href="/" className="brand"><Building2/>SMART CAMPUS</Link><p className="eyebrow">WELCOME BACK</p><h1>Find your place.</h1><p className="muted">Choose your portal to continue.</p><div className="portal-grid">{roles.map(value=>{const Icon=icons[value];return <motion.button whileHover={{y:-4}} key={value} className={"portal-card "+(role===value?"selected":"")} onClick={()=>setRole(value)} aria-pressed={role===value}><Icon/><strong>{roleLabels[value]}</strong><span>{descriptions[value]}</span></motion.button>;})}</div><section className="login-panel"><h2>{roleLabels[role]} sign in</h2>{demo?<><p className="notice">Demo environment. Explore using sample accounts; no real college records are connected.</p><Button disabled={busy} onClick={()=>signIn("demo","demo",true)}>{busy?"Opening portal…":"Open "+roleLabels[role]+" demo"}</Button><div className="quick-login" aria-label="Quick demo login">{roles.map(r=><button disabled={busy} key={r} onClick={()=>signIn("demo","demo",true,r)}>{roleLabels[r]}</button>)}</div></>:<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void signIn(String(form.get("identifier")),String(form.get("password")),false);}}><label>{role==="student"?"Roll number":"Email"}<input name="identifier" required autoComplete="username" placeholder={role==="student"?"23Z001":"name@college.edu"}/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><Button disabled={busy}>{busy?"Signing in…":"Sign in"}</Button></form>}<p className="error" role="alert">{error}</p></section></main>;}
