"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Building2,LogOut,Menu,Moon,Sun,ShieldCheck } from "lucide-react";
import type { CampusUser } from "@/lib/roles";
import { roleLabels } from "@/lib/roles";
import { Button } from "./ui/button";
export default function PortalShell({user,demo}:{user:CampusUser;demo:boolean}){const router=useRouter();const [light,setLight]=useState(false);const [collapsed,setCollapsed]=useState(false);const [error,setError]=useState("");return <main className={"portal "+(light?"light":"")}><aside className={collapsed?"collapsed":""}><Link className="brand" href="/"><Building2/>{!collapsed&&"SMART CAMPUS"}</Link><p className="eyebrow">{!collapsed&&roleLabels[user.role]}</p><nav><Link href="/portal">{collapsed?"⌂":"Dashboard"}</Link><Link href="/portal/rooms">{collapsed?"R":"Classroom finder"}</Link></nav><p className="sidebar-note">{!collapsed&&"Additional workflow pages will appear as each phase is implemented."}</p><button onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle sidebar"><Menu/></button></aside><section className="workspace"><header><span>{roleLabels[user.role]} portal</span><div><button onClick={()=>setLight(!light)} aria-label="Toggle theme">{light?<Moon/>:<Sun/>}</button><button onClick={async()=>{try{const r=await fetch("/api/auth/logout",{method:"POST"});if(!r.ok)throw new Error("Sign-out failed");router.replace("/login");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Sign-out failed");}}} aria-label="Sign out"><LogOut/></button></div></header>{demo&&<p className="notice">Demo mode · Phase 1 foundation. Sample data is separate from live campus records.</p>}<p className="eyebrow">YOUR CAMPUS WORKSPACE</p><h1>Hello, {user.name}.</h1><p className="muted">You’re signed in to the {roleLabels[user.role].toLowerCase()} portal.</p><div className="kpi-grid"><article><span>Academic blocks</span><strong>13</strong><small>Seed configuration</small></article><article><span>Sample classrooms</span><strong>650</strong><small>50 rooms per block</small></article><article><span>Your access</span><strong className="role-value">{roleLabels[user.role]}</strong><small>Checked on the server</small></article></div><section className="empty-panel"><ShieldCheck/><h2>Your portal is ready.</h2><p>The authentication and campus data foundation are in place. Timetable and classroom workflows are the next delivery phase.</p><Button variant="outline" asChild><Link href="/">Back to campus</Link></Button></section><p className="error" role="alert">{error}</p></section></main>;}
