"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { Building2,Users,CalendarDays } from "lucide-react";
import type { FinderRoom } from "@/backend/availability";
import { Button } from "./ui/button";
const labels:Record<string,string>={free:"Free",regular:"Regular class",makeup:"Makeup class",club:"Club booking",maintenance:"Maintenance",inactive:"Inactive"};
export default function RoomFinder(){const [date,setDate]=useState(()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"}));const [start,setStart]=useState("09:00");const [end,setEnd]=useState("10:00");const [capacity,setCapacity]=useState(1);const [building,setBuilding]=useState("");const [query,setQuery]=useState("");const [resource,setResource]=useState("");const [free,setFree]=useState(false);const [rooms,setRooms]=useState<FinderRoom[]>([]);const [loading,setLoading]=useState(true);const [demo,setDemo]=useState(false);const [error,setError]=useState("");const [limit,setLimit]=useState(50);
useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");setLimit(50);const timer=setTimeout(async()=>{try{const params=new URLSearchParams({date,start,end,capacity:String(capacity),building,query,resource,free:String(free)});const response=await fetch("/api/rooms?"+params,{signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);setRooms(data.rooms);setDemo(data.demo);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Room search failed");}finally{if(!controller.signal.aborted)setLoading(false);}},180);return ()=>{clearTimeout(timer);controller.abort();};},[date,start,end,capacity,building,query,resource,free]);
return <main className="finder"><nav className="topbar"><Link className="brand" href="/portal"><Building2/>SMART CAMPUS</Link><Link href="/portal">Back to dashboard</Link></nav><p className="eyebrow">A SPACE FOR YOUR NEXT CLASS</p><h1>Find a classroom.</h1><p className="muted">Availability for your chosen date and time, with working facilities.</p>{demo&&<p className="notice">Demo data: 650 generated rooms and illustrative occupancy. This does not represent your college’s live timetable.</p>}<form className="finder-filters" onSubmit={e=>e.preventDefault()}><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>From<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Until<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Minimum seats<input type="number" min="1" max="10000" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><label>Block<select value={building} onChange={e=>setBuilding(e.target.value)}><option value="">All blocks</option>{["A","B","C","D","E","F","G","I","J","K","M","T","Y"].map(b=><option key={b}>{b}</option>)}</select></label><label>Working facility<select value={resource} onChange={e=>setResource(e.target.value)}><option value="">Any</option><option value="projector">Projector</option><option value="computers">Computers</option><option value="ac">AC</option><option value="smart_board">Smart board</option><option value="lab_equipment">Lab equipment</option></select></label><label>Room number<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="C-101"/></label><label className="checkbox"><input type="checkbox" checked={free} onChange={e=>setFree(e.target.checked)}/>Free rooms only</label></form><p role="status" className={error?"error":"muted"}>{loading?"Checking availability…":error||`${rooms.length} classrooms match your filters`}</p>{!loading&&!error&&<div className="room-grid">{rooms.slice(0,limit).map(room=><article key={room.id} className="room-card"><span className={"room-status status-"+room.availability}>{labels[room.availability]??room.availability}</span><h2>{room.room_number}</h2><p><Building2 size={16}/>Block {room.building_id} · Floor {room.floor}</p><p><Users size={16}/>{room.capacity} seats · {room.room_type.replaceAll("_"," ")}</p><p><CalendarDays size={16}/>{start}–{end}</p><div className="resource-tags">{Object.entries(room.resources).map(([name,count])=><span key={name}>{name.replaceAll("_"," ")}: {count} working</span>)}</div></article>)}</div>}{!loading&&!error&&rooms.length>limit&&<Button variant="outline" onClick={()=>setLimit(limit+50)}>Show 50 more classrooms</Button>}{!loading&&!error&&rooms.length===0&&<section className="empty-panel"><h2>No matching classrooms</h2><p>Try another time, fewer seats or different facilities.</p></section>}</main>;}
