-- Run after schema.sql. Direct clients have no write access.
create function campus_role() returns text language sql stable security definer set search_path=public as $$select role from users where id=auth.uid()$$;
create function campus_section() returns text language sql stable security definer set search_path=public as $$select section_id from users where id=auth.uid()$$;
revoke all on function campus_role(),campus_section() from public;
grant execute on function campus_role(),campus_section() to authenticated;
alter table buildings enable row level security;
revoke insert,update,delete on buildings from anon,authenticated;
create policy campus_read on buildings for select to authenticated using(true);
alter table departments enable row level security;
revoke insert,update,delete on departments from anon,authenticated;
create policy campus_read on departments for select to authenticated using(true);
alter table classrooms enable row level security;
revoke insert,update,delete on classrooms from anon,authenticated;
create policy campus_read on classrooms for select to authenticated using(true);
alter table resources enable row level security;
revoke insert,update,delete on resources from anon,authenticated;
create policy campus_read on resources for select to authenticated using(true);
alter table classroom_resources enable row level security;
revoke insert,update,delete on classroom_resources from anon,authenticated;
create policy campus_read on classroom_resources for select to authenticated using(true);
alter table maintenance_blocks enable row level security;
revoke insert,update,delete on maintenance_blocks from anon,authenticated;
create policy campus_read on maintenance_blocks for select to authenticated using(true);
alter table floor_plans enable row level security;
revoke insert,update,delete on floor_plans from anon,authenticated;
create policy campus_read on floor_plans for select to authenticated using(true);
alter table room_shapes enable row level security;
revoke insert,update,delete on room_shapes from anon,authenticated;
create policy campus_read on room_shapes for select to authenticated using(true);
alter table map_nodes enable row level security;
revoke insert,update,delete on map_nodes from anon,authenticated;
create policy campus_read on map_nodes for select to authenticated using(true);
alter table map_edges enable row level security;
revoke insert,update,delete on map_edges from anon,authenticated;
create policy campus_read on map_edges for select to authenticated using(true);
alter table building_distances enable row level security;
revoke insert,update,delete on building_distances from anon,authenticated;
create policy campus_read on building_distances for select to authenticated using(true);
alter table department_home_buildings enable row level security;
revoke insert,update,delete on department_home_buildings from anon,authenticated;
create policy campus_read on department_home_buildings for select to authenticated using(true);
alter table class_sections enable row level security;
revoke insert,update,delete on class_sections from anon,authenticated;
create policy campus_read on class_sections for select to authenticated using(true);
alter table section_home_rooms enable row level security;
revoke insert,update,delete on section_home_rooms from anon,authenticated;
create policy campus_read on section_home_rooms for select to authenticated using(true);
alter table users enable row level security;
revoke insert,update,delete on users from anon,authenticated;
create policy admin_read on users for select to authenticated using(campus_role()='admin');
alter table students enable row level security;
revoke insert,update,delete on students from anon,authenticated;
create policy admin_read on students for select to authenticated using(campus_role()='admin');
alter table faculty enable row level security;
revoke insert,update,delete on faculty from anon,authenticated;
create policy admin_read on faculty for select to authenticated using(campus_role()='admin');
alter table reps enable row level security;
revoke insert,update,delete on reps from anon,authenticated;
create policy admin_read on reps for select to authenticated using(campus_role()='admin');
alter table club_profiles enable row level security;
revoke insert,update,delete on club_profiles from anon,authenticated;
create policy admin_read on club_profiles for select to authenticated using(campus_role()='admin');
alter table timetable_versions enable row level security;
revoke insert,update,delete on timetable_versions from anon,authenticated;
create policy admin_read on timetable_versions for select to authenticated using(campus_role()='admin');
alter table timetable_sessions enable row level security;
revoke insert,update,delete on timetable_sessions from anon,authenticated;
create policy admin_read on timetable_sessions for select to authenticated using(campus_role()='admin');
alter table session_occurrences enable row level security;
revoke insert,update,delete on session_occurrences from anon,authenticated;
create policy admin_read on session_occurrences for select to authenticated using(campus_role()='admin');
alter table makeup_sessions enable row level security;
revoke insert,update,delete on makeup_sessions from anon,authenticated;
create policy admin_read on makeup_sessions for select to authenticated using(campus_role()='admin');
alter table cancellation_reports enable row level security;
revoke insert,update,delete on cancellation_reports from anon,authenticated;
create policy admin_read on cancellation_reports for select to authenticated using(campus_role()='admin');
alter table classroom_issues enable row level security;
revoke insert,update,delete on classroom_issues from anon,authenticated;
create policy admin_read on classroom_issues for select to authenticated using(campus_role()='admin');
alter table rep_permissions enable row level security;
revoke insert,update,delete on rep_permissions from anon,authenticated;
create policy admin_read on rep_permissions for select to authenticated using(campus_role()='admin');
alter table room_change_log enable row level security;
revoke insert,update,delete on room_change_log from anon,authenticated;
create policy admin_read on room_change_log for select to authenticated using(campus_role()='admin');
alter table hod_consents enable row level security;
revoke insert,update,delete on hod_consents from anon,authenticated;
create policy admin_read on hod_consents for select to authenticated using(campus_role()='admin');
alter table club_bookings enable row level security;
revoke insert,update,delete on club_bookings from anon,authenticated;
create policy admin_read on club_bookings for select to authenticated using(campus_role()='admin');
alter table occupancy_reservations enable row level security;
revoke insert,update,delete on occupancy_reservations from anon,authenticated;
create policy admin_read on occupancy_reservations for select to authenticated using(campus_role()='admin');
alter table notifications enable row level security;
revoke insert,update,delete on notifications from anon,authenticated;
create policy admin_read on notifications for select to authenticated using(campus_role()='admin');
alter table whatsapp_deliveries enable row level security;
revoke insert,update,delete on whatsapp_deliveries from anon,authenticated;
create policy admin_read on whatsapp_deliveries for select to authenticated using(campus_role()='admin');
alter table audit_logs enable row level security;
revoke insert,update,delete on audit_logs from anon,authenticated;
create policy admin_read on audit_logs for select to authenticated using(campus_role()='admin');
alter table student_section_enrollments enable row level security;
revoke insert,update,delete on student_section_enrollments from anon,authenticated;
create policy admin_read on student_section_enrollments for select to authenticated using(campus_role()='admin');
alter table subject_enrollments enable row level security;
revoke insert,update,delete on subject_enrollments from anon,authenticated;
create policy admin_read on subject_enrollments for select to authenticated using(campus_role()='admin');
alter table attendance_records enable row level security;
revoke insert,update,delete on attendance_records from anon,authenticated;
create policy admin_read on attendance_records for select to authenticated using(campus_role()='admin');
alter table attendance_submissions enable row level security;
revoke insert,update,delete on attendance_submissions from anon,authenticated;
create policy admin_read on attendance_submissions for select to authenticated using(campus_role()='admin');
alter table booking_counters enable row level security;
revoke insert,update,delete on booking_counters from anon,authenticated;
create policy admin_read on booking_counters for select to authenticated using(campus_role()='admin');
alter table login_attempts enable row level security;
revoke insert,update,delete on login_attempts from anon,authenticated;
create policy admin_read on login_attempts for select to authenticated using(campus_role()='admin');
create policy own_profile on users for select to authenticated using(id=auth.uid());
create policy own_student on students for select to authenticated using(user_id=auth.uid());
create policy own_notifications on notifications for select to authenticated using(user_id=auth.uid());
create policy own_booking on club_bookings for select to authenticated using(organizer_id=auth.uid());
create policy own_permissions on rep_permissions for select to authenticated using(rep_id=auth.uid());
create policy own_attendance on attendance_records for select to authenticated using(student_id=auth.uid());
create policy teaching_sessions on timetable_sessions for select to authenticated using(faculty_id=auth.uid() or section_id=campus_section());
create policy own_makeup on makeup_sessions for select to authenticated using(faculty_id=auth.uid() or section_id=campus_section());
-- Private buckets: reads/writes must use authorized server-issued signed URLs.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('signed-letters','signed-letters',false,5242880,array['application/pdf','image/jpeg','image/png']),
('issue-photos','issue-photos',false,3145728,array['image/jpeg','image/png']) on conflict(id) do nothing;
-- Enable website notification realtime after verifying this publication exists.
alter publication supabase_realtime add table notifications;
