-- Smart Campus schema. Run once on a new Supabase project.
create extension if not exists pgcrypto;
create extension if not exists btree_gist;
create table buildings(id text primary key, name text not null, x numeric check(x between 0 and 1), y numeric check(y between 0 and 1), has_rooms boolean not null default true);
create table departments(id text primary key, name text unique not null, home_building_id text references buildings(id));
create table class_sections(id text primary key,department_id text not null references departments(id),year int not null check(year between 1 and 6),name text not null);
create table users(id uuid primary key references auth.users(id),name text not null,email text unique not null,role text not null check(role in ('admin','rep','club_member','faculty','student')),permissions text[] not null default '{}',phone text,whatsapp_consent boolean not null default false,whatsapp_consent_at timestamptz,department_id text references departments(id),department_confirmed boolean not null default false,roll_number text unique,section_id text references class_sections(id));
create table students(user_id uuid primary key references users(id),roll_number text unique not null,department_id text references departments(id),year int not null,section_id text references class_sections(id),address text,guardian_name text);
create table faculty(user_id uuid primary key references users(id),cabin_location text);
create table reps(user_id uuid primary key references users(id),section_id text not null references class_sections(id));
create table club_profiles(user_id uuid primary key references users(id),club_name text not null,department_id text references departments(id));
create table classrooms(id uuid primary key default gen_random_uuid(),building_id text not null references buildings(id),floor int not null check(floor>=0),room_number text unique not null,capacity int not null check(capacity>0),seat_rows int not null check(seat_rows>0),seat_cols int not null check(seat_cols>0),room_type text not null check(room_type in ('lecture','lab','computer_lab','seminar','auditorium')),is_active boolean not null default true,status text not null default 'active' check(status in ('active','maintenance')));
create table resources(id text primary key,name text unique not null);
create table classroom_resources(classroom_id uuid references classrooms(id),resource_id text references resources(id),quantity_available int not null check(quantity_available>=0),quantity_working int not null check(quantity_working>=0 and quantity_working<=quantity_available),primary key(classroom_id,resource_id));
create table timetable_versions(id uuid primary key default gen_random_uuid(),name text not null,status text not null check(status in ('draft','published')),effective_from date not null,effective_to date not null check(effective_to>=effective_from));
create unique index one_published_timetable on timetable_versions(status) where status='published';
create table timetable_sessions(id uuid primary key default gen_random_uuid(),version_id uuid not null references timetable_versions(id),section_id text not null references class_sections(id),faculty_id uuid not null references faculty(user_id),classroom_id uuid references classrooms(id),subject text not null,day_of_week int not null check(day_of_week between 0 and 6),start_time time not null,end_time time not null check(end_time>start_time),priority text not null default 'normal' check(priority in ('normal','high')),required_capacity int not null default 30 check(required_capacity>0),required_resources jsonb not null default '{}',room_type text not null default 'lecture');
create index recurring_room_slot on timetable_sessions(classroom_id,day_of_week,start_time);
create table session_occurrences(id uuid primary key default gen_random_uuid(),session_id uuid not null references timetable_sessions(id),occurrence_date date not null,status text not null default 'scheduled' check(status in ('scheduled','cancelled','rescheduled','room_changed')),classroom_override uuid references classrooms(id),makeup_required boolean not null default false,unique(session_id,occurrence_date));
create table makeup_sessions(id uuid primary key default gen_random_uuid(),occurrence_id uuid not null unique references session_occurrences(id),section_id text not null references class_sections(id),faculty_id uuid not null references faculty(user_id),classroom_id uuid not null references classrooms(id),event_date date not null,start_time time not null,end_time time not null check(end_time>start_time),subject text not null);
create table maintenance_blocks(id uuid primary key default gen_random_uuid(),classroom_id uuid not null references classrooms(id),event_date date not null,start_time time not null,end_time time not null check(end_time>start_time),reason text not null);
create table cancellation_reports(id uuid primary key default gen_random_uuid(),occurrence_id uuid not null references session_occurrences(id),rep_id uuid not null references reps(user_id),reason text not null,status text not null default 'pending' check(status in ('pending','approved','rejected')),decision_reason text,created_at timestamptz not null default now());
create table classroom_issues(id uuid primary key default gen_random_uuid(),classroom_id uuid not null references classrooms(id),occurrence_id uuid not null references session_occurrences(id),rep_id uuid not null references reps(user_id),type text not null,description text not null,image_url text,status text not null default 'pending' check(status in ('pending','acknowledged','resolved','rejected')),created_at timestamptz default now());
create table rep_permissions(id uuid primary key default gen_random_uuid(),rep_id uuid not null references reps(user_id),occurrence_id uuid not null references session_occurrences(id),reason text not null,status text not null default 'pending' check(status in ('pending','approved','rejected','expired','used','revoked')),expires_at timestamptz,used_at timestamptz,created_at timestamptz not null default now());
create table room_change_log(id uuid primary key default gen_random_uuid(),occurrence_id uuid not null references session_occurrences(id),permission_id uuid unique references rep_permissions(id),old_classroom_id uuid references classrooms(id),new_classroom_id uuid not null references classrooms(id),actor_id uuid not null references users(id),created_at timestamptz not null default now());
create table hod_consents(id uuid primary key default gen_random_uuid(),occurrence_id uuid not null references session_occurrences(id),status text not null default 'pending' check(status in ('pending','accepted','declined')),reason text not null,decision_note text,compromise jsonb,actor_id uuid references users(id),created_at timestamptz not null default now());
create table booking_counters(year int primary key,value int not null check(value>0));
create function next_booking_reference() returns text language plpgsql security definer set search_path=public as $$declare yr int:=extract(year from now() at time zone 'Asia/Kolkata');n int;begin insert into booking_counters values(yr,1) on conflict(year) do update set value=booking_counters.value+1 returning value into n;return 'CLUB-'||yr||'-'||lpad(n::text,greatest(4,length(n::text)),'0');end$$;
create table club_bookings(id uuid primary key default gen_random_uuid(),reference_no text unique not null default next_booking_reference(),organizer_id uuid not null references users(id),club text not null,organizer text not null,department_id text references departments(id),faculty_coordinator uuid references faculty(user_id),event text not null,purpose text not null,event_date date not null,start_time time not null,end_time time not null check(end_time>start_time),participants int not null check(participants>0),resources jsonb not null default '{}',classroom_id uuid not null references classrooms(id),status text not null default 'draft' check(status in ('draft','awaiting_hod_signature','signed_letter_submitted','approved','rejected','cancelled')),letter_pdf_url text,signed_letter_url text,decision_reason text,created_at timestamptz not null default now());
create index booking_room_slot on club_bookings(classroom_id,event_date,start_time);
-- A transactional reservation ledger is populated by approval/publish RPCs.
-- Exclusion constraints protect every room, faculty and section against races.
create table occupancy_reservations(id uuid primary key default gen_random_uuid(),source_kind text not null,source_id uuid not null,classroom_id uuid not null references classrooms(id),faculty_id uuid references faculty(user_id),section_id text references class_sections(id),slot tsrange not null,unique(source_kind,source_id),exclude using gist(classroom_id with =,slot with &&),exclude using gist(faculty_id with =,slot with &&) where(faculty_id is not null),exclude using gist(section_id with =,slot with &&) where(section_id is not null));
create table notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id),event text not null,title text not null,body text not null,read_at timestamptz,created_at timestamptz not null default now());
create table whatsapp_deliveries(id uuid primary key default gen_random_uuid(),notification_id uuid not null references notifications(id),user_id uuid not null references users(id),status text not null default 'queued' check(status in ('queued','sent','delivered','read','failed','skipped_no_consent')),mode text not null default 'mock' check(mode in ('mock','live')),provider_id text,error text,attempts int not null default 0,created_at timestamptz not null default now());
create table audit_logs(id bigint generated always as identity primary key,actor_id uuid references users(id),action text not null,entity text not null,entity_id text,before jsonb,after jsonb,created_at timestamptz not null default now());
create function forbid_audit_change() returns trigger language plpgsql as $$begin raise exception 'Audit logs are append-only';end$$;
create trigger audit_immutable before update or delete on audit_logs for each row execute function forbid_audit_change();
create table student_section_enrollments(student_id uuid references students(user_id),section_id text references class_sections(id),primary key(student_id,section_id));
create table subject_enrollments(student_id uuid references students(user_id),subject text not null,batch text,primary key(student_id,subject));
create table attendance_submissions(id uuid primary key default gen_random_uuid(),session_id uuid references timetable_sessions(id),makeup_id uuid references makeup_sessions(id),event_date date not null,faculty_id uuid not null references faculty(user_id),locked boolean not null default true,submitted_at timestamptz not null default now(),check((session_id is null)<>(makeup_id is null)));
create unique index attendance_regular_unique on attendance_submissions(session_id,event_date) where session_id is not null;
create unique index attendance_makeup_unique on attendance_submissions(makeup_id) where makeup_id is not null;
create table attendance_records(id uuid primary key default gen_random_uuid(),submission_id uuid not null references attendance_submissions(id),student_id uuid not null references students(user_id),status text not null check(status in ('present','absent','late','on_duty','excused')),edit_reason text,unique(submission_id,student_id));
create table floor_plans(id uuid primary key default gen_random_uuid(),building_id text not null references buildings(id),floor int not null,image_url text,width int not null default 1000,height int not null default 600,unique(building_id,floor));
create table room_shapes(classroom_id uuid primary key references classrooms(id),floor_plan_id uuid not null references floor_plans(id),x numeric not null check(x between 0 and 1),y numeric not null check(y between 0 and 1),width numeric not null check(width>0 and width<=1),height numeric not null check(height>0 and height<=1),check(x+width<=1 and y+height<=1));
create table map_nodes(id uuid primary key default gen_random_uuid(),label text,kind text not null,building_id text references buildings(id),floor int,x numeric not null check(x between 0 and 1),y numeric not null check(y between 0 and 1));
create table map_edges(id uuid primary key default gen_random_uuid(),from_node uuid not null references map_nodes(id),to_node uuid not null references map_nodes(id),meters numeric not null check(meters>0),accessible boolean not null default true,unique(from_node,to_node));
create table section_home_rooms(section_id text primary key references class_sections(id),classroom_id uuid not null references classrooms(id));
create table department_home_buildings(department_id text primary key references departments(id),building_id text not null references buildings(id));
create table building_distances(from_building text references buildings(id),to_building text references buildings(id),meters numeric not null check(meters>=0),primary key(from_building,to_building));
create table login_attempts(key text primary key,window_started timestamptz not null,attempts int not null);
create function allow_login_attempt(attempt_key text) returns boolean language plpgsql security definer set search_path=public as $$declare n int;begin insert into login_attempts values(attempt_key,now(),1) on conflict(key) do update set attempts=case when login_attempts.window_started<now()-interval '15 minutes' then 1 else login_attempts.attempts+1 end,window_started=case when login_attempts.window_started<now()-interval '15 minutes' then now() else login_attempts.window_started end returning attempts into n;return n<=5;end$$;
create function confirm_student_department(chosen_department text,consent boolean,actor_id uuid) returns void language plpgsql security definer set search_path=public as $$declare prior jsonb;begin select to_jsonb(u) into prior from users u where id=actor_id and role='student' and not department_confirmed for update;if prior is null then raise exception 'Not an unconfirmed student';end if;update users set department_id=chosen_department,department_confirmed=true,whatsapp_consent=consent,whatsapp_consent_at=case when consent then now() else null end where id=actor_id;update students set department_id=chosen_department where user_id=actor_id;insert into audit_logs(actor_id,action,entity,entity_id,before,after) values(actor_id,'department_confirmed','users',actor_id::text,prior,jsonb_build_object('department_id',chosen_department,'whatsapp_consent',consent));insert into notifications(user_id,event,title,body) values(actor_id,'department_confirmed','Department confirmed','Your department preference has been saved.');end$$;
-- Expand only the published timetable, and layer date-specific overrides on it.
create view room_occupancy with (security_invoker=true) as
select coalesce(o.classroom_override,s.classroom_id) classroom_id,d::date event_date,s.start_time,s.end_time,'regular'::text source_kind,s.id source_id,s.faculty_id,s.section_id
from timetable_sessions s join timetable_versions v on v.id=s.version_id and v.status='published'
cross join lateral generate_series(v.effective_from::timestamp,v.effective_to::timestamp,interval '1 day') d
left join session_occurrences o on o.session_id=s.id and o.occurrence_date=d::date
where extract(dow from d)=s.day_of_week and coalesce(o.status,'scheduled') not in ('cancelled','rescheduled')
union all select classroom_id,event_date,start_time,end_time,'makeup',id,faculty_id,section_id from makeup_sessions
union all select classroom_id,event_date,start_time,end_time,'club',id,null,null from club_bookings where status='approved'
union all select classroom_id,event_date,start_time,end_time,'maintenance',id,null,null from maintenance_blocks;
create index notifications_user_time on notifications(user_id,created_at desc);
create index occurrences_session_date on session_occurrences(session_id,occurrence_date);
create index audit_actor_time on audit_logs(actor_id,created_at desc);
revoke all on function next_booking_reference() from public,anon,authenticated;
revoke all on function allow_login_attempt(text) from public,anon,authenticated;
revoke all on function confirm_student_department(text,boolean,uuid) from public,anon,authenticated;
grant execute on function next_booking_reference(),allow_login_attempt(text),confirm_student_department(text,boolean,uuid) to service_role;
